service: hello
runtime: go
api_version: go1

# /Users/unders/go1.6/bin
# export PATH=/Users/unders/go1.6/bin:$PATH

# When using automatic scaling, the F1, F2, F4, and F4_1G instance classes are available.
#instance_class: F1
#automatic_scaling:
#  min_idle_instances: 5
#  max_idle_instances: automatic  # default value
#  min_pending_latency: 30ms  # default value
#  max_pending_latency: automatic
#  max_concurrent_requests: 50

# https://cloud.google.com/appengine/docs/standard/go/warmup-requests/configuring
inbound_services:
  - warmup

handlers:
- url: /_ah/warmup
  script: _go_app
  login: admin

- url: /.*
  secure: always
  script: _go_app


skip_files:
- ^Makefile$

#error_handlers:
#  - file: default_error.html
#
#  - error_code: over_quota
#    file: over_quota.html

# https://github.com/GoogleCloudPlatform/golang-samples/tree/master/docs/appengine
# https://cloud.google.com/appengine/docs/standard/go/config/appref
# https://blog.golang.org/the-app-engine-sdk-and-workspaces-gopath
# https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/examples/storage/appengine
